<?php
header("Content-type:text/plain;charset=utf8");
require_once '../C/UserController.php';

use C\UserController;

echo "Test sur le UserController\n";
echo "---------------------------\n";

echo "Test 1 : Utilisateur loggué par défaut";
$c = new UserController();
echo "\nCurrent User : ";
var_dump(UserController::getCurrentUser());
echo "\n";
echo "Lire : ".(($c->permit("lire"))?"OK":"KO");
echo "\n";
echo "Ecrire : ".(($c->permit("ecrire"))?"OK":"KO");
echo "\n";
echo "Modifier : ".(($c->permit("modifier"))?"OK":"KO");
echo "\n";
echo "Delete : ".(($c->permit("supprimer"))?"OK":"KO");
echo "\n";
echo "---------------------------\n";
$log = $c->login("toto", "titi");
echo "Test 2 : utilisateur non enregistré";
echo "\n";
echo "\n";
echo "mauvais login : ".(($log)?"KO":"OK");
echo "\nCurrent User : ";
var_dump(UserController::getCurrentUser());
echo "\n";
echo "Lire : ".(($c->permit("lire"))?"OK":"KO");
echo "\n";
echo "Ecrire : ".(($c->permit("ecrire"))?"OK":"KO");
echo "\n";
echo "Modifier : ".(($c->permit("modifier"))?"OK":"KO");
echo "\n";
echo "Delete : ".(($c->permit("supprimer"))?"OK":"KO");
echo "\n";

echo "\n";
echo "---------------------------\n";
$log = $c->login("Dragon Rouge", "titi");
echo "Test 3 : utilisateur propriétaire";
echo "\n";
echo "\n";
echo "Bon login : ".(($log)?"OK":"KO");
echo "\nCurrent User : ";
var_dump(UserController::getCurrentUser());
echo "\n";
echo "\n";
echo "Lire : ".(($c->permit("lire"))?"OK":"KO");
echo "\n";
echo "Ecrire : ".(($c->permit("ecrire"))?"OK":"KO");
echo "\n";
echo "Modifier : ".(($c->permit("modifier"))?"OK":"KO");
echo "\n";
echo "Delete : ".(($c->permit("supprimer"))?"OK":"KO");
echo "\n";
echo "---------------------------\n";

echo "\n";
echo "---------------------------\n";
$log = $c->login("carme", "toto");
echo "Test 3 : utilisateur collaborateur";
echo "\n";
echo "\n";
echo "Bon login : ".(($log)?"OK":"KO");
echo "\nCurrent User : ";
var_dump(UserController::getCurrentUser());
echo "\n";
echo "\n";
echo "Lire : ".(($c->permit("lire"))?"OK":"KO");
echo "\n";
echo "Ecrire : ".(($c->permit("ecrire"))?"OK":"KO");
echo "\n";
echo "Modifier : ".(($c->permit("modifier"))?"OK":"KO");
echo "\n";
echo "Delete : ".(($c->permit("supprimer"))?"OK":"KO");
echo "\n";
echo "---------------------------\n";

echo "\n";
echo "---------------------------\n";
$log = $c->login("emi", "lapin");
echo "Test 4 : utilisateur lecteur";
echo "\n";
echo "\n";
echo "Bon login : ".(($log)?"OK":"KO");
echo "\nCurrent User : ";
var_dump(UserController::getCurrentUser());
echo "\n";
echo "\n";
echo "Lire : ".(($c->permit("lire"))?"OK":"KO");
echo "\n";
echo "Ecrire : ".(($c->permit("ecrire"))?"OK":"KO");
echo "\n";
echo "Modifier : ".(($c->permit("modifier"))?"OK":"KO");
echo "\n";
echo "Delete : ".(($c->permit("supprimer"))?"OK":"KO");
echo "\n";
echo "---------------------------\n";