<?php

namespace M\Utils;
require_once __DIR__.'/../../../M/Utils/DateTimeUtils.php';
use M\Utils\DateTimeUtils;
/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-06-24 at 11:58:15.
 */
class DateTimeUtilsTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DateTimeUtils
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
       
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers M\Utils\DateTimeUtils::getFirstDateTimeOfMonth
     * @todo   Implement testGetFirstDateTimeOfMonth().
     */
    public function testGetFirstDateTimeOfMonth() {
        $date = new \DateTime();
        $fd = DateTimeUtils::getFirstDateTimeOfMonth($date);
        $this->assertEquals($fd,new \DateTime("2016-06-01"));
    }

    /**
     * @covers M\Utils\DateTimeUtils::getLastDateTimeOfMonth
     * @todo   Implement testGetLastDateTimeOfMonth().
     */
    public function testGetLastDateTimeOfMonth() {
        $date = new \DateTime();
        $fd = DateTimeUtils::getLastDateTimeOfMonth($date);
        $this->assertEquals($fd,new \DateTime("2016-06-30"));
    }

    /**
     * @covers M\Utils\DateTimeUtils::getFirstDateTimeOfWeek
     * @todo   Implement testGetFirstDateTimeOfWeek().
     */
    public function testGetFirstDateTimeOfWeek() {
        $date = new \DateTime();
        $fd = DateTimeUtils::getFirstDateTimeOfWeek($date);
        //$this->assertEquals($fd,new \DateTime("2016-06-20"));
    }

    /**
     * @covers M\Utils\DateTimeUtils::getLastDateTimeOfWeek
     * @todo   Implement testGetLastDateTimeOfWeek().
     */
    public function testGetLastDateTimeOfWeek() {
         $date = new \DateTime();
        $fd = DateTimeUtils::getLastDateTimeOfWeek($date);
        //$this->assertEquals($fd,new \DateTime("2016-06-26"));
    }

}
